//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.ReferenciaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Libro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cod_libroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        private int AñoField;
        
        private System.Nullable<Biblioteca.ReferenciaServicio.TipoUsuario> TipoField;
        
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cod_libro {
            get {
                return this.cod_libroField;
            }
            set {
                if ((this.cod_libroField.Equals(value) != true)) {
                    this.cod_libroField = value;
                    this.RaisePropertyChanged("cod_libro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Año {
            get {
                return this.AñoField;
            }
            set {
                if ((this.AñoField.Equals(value) != true)) {
                    this.AñoField = value;
                    this.RaisePropertyChanged("Año");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<Biblioteca.ReferenciaServicio.TipoUsuario> Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuario", Namespace="http://tempuri.org/")]
    public enum TipoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reserva = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicio.ServicioBibliotecaSoap")]
    public interface ServicioBibliotecaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Biblioteca.ReferenciaServicio.HelloWorldResponse HelloWorld(Biblioteca.ReferenciaServicio.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Biblioteca.ReferenciaServicio.HelloWorldResponse> HelloWorldAsync(Biblioteca.ReferenciaServicio.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento busquedalibros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarLibros", ReplyAction="*")]
        Biblioteca.ReferenciaServicio.buscarLibrosResponse buscarLibros(Biblioteca.ReferenciaServicio.buscarLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarLibros", ReplyAction="*")]
        System.Threading.Tasks.Task<Biblioteca.ReferenciaServicio.buscarLibrosResponse> buscarLibrosAsync(Biblioteca.ReferenciaServicio.buscarLibrosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca.ReferenciaServicio.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Biblioteca.ReferenciaServicio.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca.ReferenciaServicio.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Biblioteca.ReferenciaServicio.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarLibrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarLibros", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca.ReferenciaServicio.buscarLibrosRequestBody Body;
        
        public buscarLibrosRequest() {
        }
        
        public buscarLibrosRequest(Biblioteca.ReferenciaServicio.buscarLibrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarLibrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string busquedalibros;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string area;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string autor;
        
        public buscarLibrosRequestBody() {
        }
        
        public buscarLibrosRequestBody(string busquedalibros, string tipo, string area, string autor) {
            this.busquedalibros = busquedalibros;
            this.tipo = tipo;
            this.area = area;
            this.autor = autor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarLibrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Biblioteca.ReferenciaServicio.buscarLibrosResponseBody Body;
        
        public buscarLibrosResponse() {
        }
        
        public buscarLibrosResponse(Biblioteca.ReferenciaServicio.buscarLibrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarLibrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Biblioteca.ReferenciaServicio.Libro[] buscarLibrosResult;
        
        public buscarLibrosResponseBody() {
        }
        
        public buscarLibrosResponseBody(Biblioteca.ReferenciaServicio.Libro[] buscarLibrosResult) {
            this.buscarLibrosResult = buscarLibrosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioBibliotecaSoapChannel : Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBibliotecaSoapClient : System.ServiceModel.ClientBase<Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap>, Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap {
        
        public ServicioBibliotecaSoapClient() {
        }
        
        public ServicioBibliotecaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBibliotecaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBibliotecaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBibliotecaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biblioteca.ReferenciaServicio.HelloWorldResponse Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap.HelloWorld(Biblioteca.ReferenciaServicio.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Biblioteca.ReferenciaServicio.HelloWorldRequest inValue = new Biblioteca.ReferenciaServicio.HelloWorldRequest();
            inValue.Body = new Biblioteca.ReferenciaServicio.HelloWorldRequestBody();
            Biblioteca.ReferenciaServicio.HelloWorldResponse retVal = ((Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Biblioteca.ReferenciaServicio.HelloWorldResponse> Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap.HelloWorldAsync(Biblioteca.ReferenciaServicio.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Biblioteca.ReferenciaServicio.HelloWorldResponse> HelloWorldAsync() {
            Biblioteca.ReferenciaServicio.HelloWorldRequest inValue = new Biblioteca.ReferenciaServicio.HelloWorldRequest();
            inValue.Body = new Biblioteca.ReferenciaServicio.HelloWorldRequestBody();
            return ((Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biblioteca.ReferenciaServicio.buscarLibrosResponse Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap.buscarLibros(Biblioteca.ReferenciaServicio.buscarLibrosRequest request) {
            return base.Channel.buscarLibros(request);
        }
        
        public Biblioteca.ReferenciaServicio.Libro[] buscarLibros(string busquedalibros, string tipo, string area, string autor) {
            Biblioteca.ReferenciaServicio.buscarLibrosRequest inValue = new Biblioteca.ReferenciaServicio.buscarLibrosRequest();
            inValue.Body = new Biblioteca.ReferenciaServicio.buscarLibrosRequestBody();
            inValue.Body.busquedalibros = busquedalibros;
            inValue.Body.tipo = tipo;
            inValue.Body.area = area;
            inValue.Body.autor = autor;
            Biblioteca.ReferenciaServicio.buscarLibrosResponse retVal = ((Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap)(this)).buscarLibros(inValue);
            return retVal.Body.buscarLibrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Biblioteca.ReferenciaServicio.buscarLibrosResponse> Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap.buscarLibrosAsync(Biblioteca.ReferenciaServicio.buscarLibrosRequest request) {
            return base.Channel.buscarLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Biblioteca.ReferenciaServicio.buscarLibrosResponse> buscarLibrosAsync(string busquedalibros, string tipo, string area, string autor) {
            Biblioteca.ReferenciaServicio.buscarLibrosRequest inValue = new Biblioteca.ReferenciaServicio.buscarLibrosRequest();
            inValue.Body = new Biblioteca.ReferenciaServicio.buscarLibrosRequestBody();
            inValue.Body.busquedalibros = busquedalibros;
            inValue.Body.tipo = tipo;
            inValue.Body.area = area;
            inValue.Body.autor = autor;
            return ((Biblioteca.ReferenciaServicio.ServicioBibliotecaSoap)(this)).buscarLibrosAsync(inValue);
        }
    }
}
